# Generated by Django 5.0.4 on 2024-05-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('modelmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferencedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('inf_image_path', models.CharField(blank=True, max_length=250, null=True)),
                ('detection_info', models.JSONField(blank=True, null=True)),
                ('ai_model', models.CharField(blank=True, choices=[('vggnet.pt', 'vggnet.pt')], default=('vggnet.pt', 'vggnet.pt'), help_text='Selected yolo model will download.                                  Requires an active internet connection.', max_length=250, null=True, verbose_name='AI Models')),
                ('model_conf', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Model confidence')),
                ('custom_model', models.ForeignKey(blank=True, help_text='Machine Learning model for detection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detectedimages', to='modelmanager.mlmodel', verbose_name='Custom ML Models')),
                ('orig_image', models.ForeignKey(blank=True, help_text='Main Image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detectedimages', to='images.imagefile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
